// Code generated by COMMENTS_BUILD_TOOLS 2.0.77. DO NOT EDIT.
package model

import (
	"time"
)

func (TAgentNamespace) TableName() string {
	return "t_agent_namespace"
}

func NewTAgentNamespace() *TAgentNamespace {
	return &TAgentNamespace{}
}

type TAgentNamespace struct {
	NamespaceId  int64     `gorm:"column:namespace_id;primary_key" json:"namespace_id"`          // namespace id generated by id generator
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`                          // create time
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`                          // update time
	Namespace    string    `gorm:"column:namespace;uniqueIndex:uniq_namespace" json:"namespace"` // business namespace, global unique
	Description  string    `gorm:"column:description" json:"description"`                        // namespace description
	CreatedBy    string    `gorm:"column:created_by" json:"created_by"`                          // creator identity
	MetadataJson string    `gorm:"column:metadata_json" json:"metadata_json"`                    // lightweight extension metadata in json
}
