// Code generated by COMMENTS_BUILD_TOOLS 2.0.77. DO NOT EDIT.
package model

import (
	"time"
)

func (TEventLog) TableName() string {
	return "t_event_log"
}

func NewTEventLog() *TEventLog {
	return &TEventLog{}
}

type TEventLog struct {
	EventId      int64     `gorm:"column:event_id;primary_key" json:"event_id"` // event id generated by id generator and used as cursor
	ThreadId     int64     `gorm:"column:thread_id" json:"thread_id"`           // owner thread id
	InThreadSeq  int64     `gorm:"column:in_thread_seq" json:"in_thread_seq"`   // producer-provided sequence within owner thread
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`         // create time
	Namespace    string    `gorm:"column:namespace" json:"namespace"`           // tenant namespace
	SessionId    string    `gorm:"column:session_id" json:"session_id"`         // owner session id resolved from thread at write time
	TurnId       string    `gorm:"column:turn_id" json:"turn_id"`               // logical turn id, usually triggered by one input message
	EventType    string    `gorm:"column:event_type" json:"event_type"`         // business-defined event type
	Payload      string    `gorm:"column:payload" json:"payload"`               // opaque business event payload
	MetadataJson string    `gorm:"column:metadata_json" json:"metadata_json"`   // lightweight extension metadata in json
}
