// Code generated by COMMENTS_BUILD_TOOLS 2.0.77. DO NOT EDIT.
package model

import (
	"time"
)

func (TMailboxMessage) TableName() string {
	return "t_mailbox_message"
}

func NewTMailboxMessage() *TMailboxMessage {
	return &TMailboxMessage{}
}

type TMailboxMessage struct {
	MessageId     int64     `gorm:"column:message_id;primary_key" json:"message_id"` // message id generated by id generator
	ThreadId      int64     `gorm:"column:thread_id" json:"thread_id"`               // owner thread id
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`             // create time
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`             // update time
	HandledAt     time.Time `gorm:"column:handled_at" json:"handled_at"`             // time when message enters terminal state
	SenderType    string    `gorm:"column:sender_type" json:"sender_type"`           // sender type: user system agent
	SenderId      string    `gorm:"column:sender_id" json:"sender_id"`               // sender identity
	MessageType   string    `gorm:"column:message_type" json:"message_type"`         // business-defined message type
	Status        string    `gorm:"column:status" json:"status"`                     // message status: pending acked canceled
	Payload       string    `gorm:"column:payload" json:"payload"`                   // opaque business payload
	MetadataJson  string    `gorm:"column:metadata_json" json:"metadata_json"`       // lightweight extension metadata in json
	TriggerTurnId string    `gorm:"column:trigger_turn_id" json:"trigger_turn_id"`   // turn id triggered by this message ack
}
