// Code generated by COMMENTS_BUILD_TOOLS 2.0.77. DO NOT EDIT.
package model

import (
	"time"
)

func (TThread) TableName() string {
	return "t_thread"
}

func NewTThread() *TThread {
	return &TThread{}
}

type TThread struct {
	ThreadId        int64     `gorm:"column:thread_id;primary_key" json:"thread_id"`     // thread id generated by id generator
	ReadyAt         time.Time `gorm:"column:ready_at" json:"ready_at"`                   // time when thread most recently entered ready
	LeaseDeadlineAt time.Time `gorm:"column:lease_deadline_at" json:"lease_deadline_at"` // current lease deadline
	LastActiveAt    time.Time `gorm:"column:last_active_at" json:"last_active_at"`       // last user or worker activity time
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`               // create time
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`               // update time
	ClosedAt        time.Time `gorm:"column:closed_at" json:"closed_at"`                 // close time when thread enters closed
	Namespace       string    `gorm:"column:namespace" json:"namespace"`                 // tenant namespace
	Env             string    `gorm:"column:env" json:"env"`                             // lane environment for ppe isolation
	UserId          int64     `gorm:"column:user_id" json:"user_id"`                     // owner user id, 0 means unknown or system
	SessionId       string    `gorm:"column:session_id" json:"session_id"`               // owner session id for streamout aggregation
	Title           string    `gorm:"column:title" json:"title"`                         // thread title
	Status          string    `gorm:"column:status" json:"status"`                       // thread status: idle ready running blocked closed
	StatusReason    string    `gorm:"column:status_reason" json:"status_reason"`         // latest status transition reason
	LeaseToken      string    `gorm:"column:lease_token" json:"lease_token"`             // current lease token, hidden from ordinary query api
	LeaseOwnerHint  string    `gorm:"column:lease_owner_hint" json:"lease_owner_hint"`   // debug hint for current lease holder
	CreatedBy       string    `gorm:"column:created_by" json:"created_by"`               // creator identity
	MetadataJson    string    `gorm:"column:metadata_json" json:"metadata_json"`         // lightweight extension metadata in json
	Profile         string    `gorm:"column:profile" json:"profile"`                     // thread profile in json
}
