# Auto-migrate from Data CI config [2020-09-06 19:57:31]
# For details: https://bytedance.feishu.cn/wiki/wikcnEl8BfuKBWxkNJB7vCPhwme
name: Test
trigger:
  change:
    types:
      - create
      - push
      - submit
jobs:
  unit_test:
    name: Project Unit Test
    image: hub.byted.org/codebase/ci_go_1_24:latest
    runs-on:
      env: boe
    steps:
      - id: unit_test
        uses: actions/codecov
        inputs: # 没有 file 参数，也就是使用v2
          commands:
            - curl http://codebaseci.byted.org/ci/open/setup_consul.sh | bash
            - export IS_SYSTEM_TEST_ENV=1 && export TESTING_PREFIX=offline && export CONF_ENV=BOE
            - export BYTED_HOST_IPV6=::1
            - go version
            - go test -gcflags=all=-l -coverprofile=coverage.out ./...
  code_quality_inspection:
    name: Code quality inspection
    image: hub.byted.org/codebase/ci_go_1_24:latest
    runs-on:
      env: boe
    steps:
      - name: Sonar
        uses: actions/sonar@v1
        inputs:
          coverage_path: coverage.txt
          coverage_type: go
          disable_quality_gates: true
          exclusions_list:
            - cmd/**
            - conf/**
            - docs/**
            - idl/**
            - kitex_gen/**
            - script/**
            - script_dmp/**
            - "**/testing/*.go"
            - "**/mocks/*.go"
            - "**/*_gen.go"
            - dals/**
            - cmd/**
          language: go