CREATE TABLE t_agent_namespace (
  namespace_id BIGINT UNSIGNED NOT NULL COMMENT 'namespace id generated by id generator',
  namespace VARCHAR(128) NOT NULL COMMENT 'business namespace, global unique',
  description VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'namespace description',
  created_by VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'creator identity',
  metadata_json TEXT COMMENT 'lightweight extension metadata in json',
  created_at DATETIME(6) NOT NULL COMMENT 'create time',
  updated_at DATETIME(6) NOT NULL COMMENT 'update time',
  PRIMARY KEY (namespace_id),
  UNIQUE KEY uniq_namespace (namespace),
  KEY idx_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='agent namespace registry table';
