CREATE TABLE t_mailbox_message (
  message_id BIGINT UNSIGNED NOT NULL COMMENT 'message id generated by id generator',
  thread_id BIGINT UNSIGNED NOT NULL COMMENT 'owner thread id',
  sender_type VARCHAR(32) NOT NULL COMMENT 'sender type: user system agent',
  sender_id VARCHAR(256) NOT NULL COMMENT 'sender identity',
  message_type VARCHAR(64) NOT NULL COMMENT 'business-defined message type',
  status VARCHAR(32) NOT NULL COMMENT 'message status: pending acked canceled',
  payload MEDIUMBLOB COMMENT 'opaque business payload',
  metadata_json TEXT COMMENT 'lightweight extension metadata in json',
  created_at DATETIME(6) NOT NULL COMMENT 'create time',
  updated_at DATETIME(6) NOT NULL COMMENT 'update time',
  handled_at DATETIME(6) NULL COMMENT 'time when message enters terminal state',
  trigger_turn_id VARCHAR(128) NULL COMMENT 'turn id triggered by this message ack',
  PRIMARY KEY (message_id),
  KEY idx_thread_status_message (thread_id, status),
  KEY idx_thread_created_at (thread_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='thread mailbox durable message table';
