CREATE TABLE t_memory_stage2_job (
  id BIGINT NOT NULL COMMENT 'database row id generated by caller-provided id generator',
  user_id VARCHAR(128) NOT NULL COMMENT 'memory owner user id',
  status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'stage2 job status',
  input_watermark VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'latest pending stage1 input watermark',
  last_success_watermark VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'stage1 input watermark completed by last successful stage2',
  last_success_at DATETIME(6) DEFAULT NULL COMMENT 'last successful stage2 completion time',
  stage2_thread_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'bound memory_consolidation thread id',
  lease_owner VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'stage2 lease owner',
  ownership_token VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'stage2 lease token',
  lease_until DATETIME(6) DEFAULT NULL COMMENT 'stage2 lease expiry',
  retry_at DATETIME(6) DEFAULT NULL COMMENT 'earliest retry time after failed stage2',
  last_error TEXT COMMENT 'latest stage2 error summary',
  updated_at DATETIME(6) DEFAULT NULL COMMENT 'row update time',
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user (user_id),
  KEY idx_stage2_claim (status, retry_at, lease_until, updated_at),
  KEY idx_stage2_thread (stage2_thread_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='DeepAgent worker memory stage2 user jobs';
