CREATE TABLE t_memory_stage1_output (
  id BIGINT NOT NULL COMMENT 'database row id generated by caller-provided id generator',
  stage1_key VARCHAR(64) NOT NULL COMMENT 'stable logical stage1 output key',
  user_id VARCHAR(128) NOT NULL COMMENT 'memory owner user id',
  source_thread_id VARCHAR(128) NOT NULL COMMENT 'source Agent Coordinator thread id',
  source_turn_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'source turn id when available',
  raw_memory MEDIUMTEXT COMMENT 'stage1 raw memory extracted from source history',
  rollout_summary MEDIUMTEXT COMMENT 'stage1 source rollout summary',
  status VARCHAR(32) NOT NULL DEFAULT 'succeeded' COMMENT 'stage1 output status',
  error_summary TEXT COMMENT 'stage1 extraction error summary',
  generated_at DATETIME(6) DEFAULT NULL COMMENT 'stage1 generation time',
  source_updated_at DATETIME(6) DEFAULT NULL COMMENT 'source history watermark used by this output',
  usage_count INT NOT NULL DEFAULT 0 COMMENT 'future memory usage count',
  last_used_at DATETIME(6) DEFAULT NULL COMMENT 'future memory usage update time',
  PRIMARY KEY (id),
  UNIQUE KEY uniq_stage1_key (stage1_key),
  KEY idx_user_source (user_id, source_thread_id, source_updated_at),
  KEY idx_user_generated (user_id, generated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='AIC Agent SDK worker memory stage1 outputs';
