CREATE TABLE t_memory_baseline (
  id BIGINT NOT NULL COMMENT 'database row id generated by caller-provided id generator',
  user_id VARCHAR(128) NOT NULL COMMENT 'memory owner user id',
  hash VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'last successful memory workspace input baseline hash',
  updated_at DATETIME(6) DEFAULT NULL COMMENT 'baseline update time',
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='DeepAgent worker memory consolidation baseline';
