// Code generated by hertztool.

package apiapp

import "code.byted.org/middleware/hertz/pkg/app/server"

const defaultServerAddress = ":6789"

func NewServer(address string) (h *server.Hertz) {
	if address == "" {
		address = defaultServerAddress
	}
	h = server.Default(
		server.WithHostPorts(address),
		server.WithSenseClientDisconnection(true),
	)
	return
}
