// Code generated by hertztool

package apiapp

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	handler "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.POST("/ad/deep_agent_sdk/ping", handler.Ping)
	r.GET("/", handler.WebApp)
	r.GET("/static/*filepath", handler.WebAsset)
	r.GET("/favicon.svg", handler.WebRootAsset)
	r.GET("/favicon.ico", handler.Favicon)
	r.POST("/ad/deep_agent_sdk/list_projects", handler.ListProjects)
	r.POST("/ad/deep_agent_sdk/close_project", handler.CloseProject)
	r.POST("/ad/deep_agent_sdk/list_changes", handler.ListChanges)
	r.POST("/ad/deep_agent_sdk/get_diff", handler.GetDiff)
	r.POST("/ad/deep_agent_sdk/list_files", handler.ListFiles)
	r.GET("/ad/deep_agent_sdk/file", handler.ServeFile)

	// your code ...
}
