// Code generated by hertztool. DO NOT EDIT.

package apiapp

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	router "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/biz/router"
)

// register registers all routers.
func Register(r *server.Hertz) {

	router.GeneratedRegister(r)

	customizedRegister(r)

}
