// Code generated by hertztool.

package handler

import (
	"context"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	aic_agent_sdk_api "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/hertz_gen/aic_agent_sdk_api"
	apitimeline "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/service/timeline"
)

// ListTimeline .
// @router /ad/aic_agent_sdk/list_timeline [POST]
func ListTimeline(ctx context.Context, c *app.RequestContext) {
	var req aic_agent_sdk_api.ListTimelineHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.ListTimelineHTTPResponse{BaseResp: baseResp})
		return
	}
	resp, err := apitimeline.List(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.ListTimelineHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}
