// Code generated by hertztool.

package handler

import (
	"context"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	aic_agent_sdk_api "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/hertz_gen/aic_agent_sdk_api"
	apicontrol "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/service/control"
)

// StopRunning .
// @router /ad/aic_agent_sdk/stop_running [POST]
func StopRunning(ctx context.Context, c *app.RequestContext) {
	var req aic_agent_sdk_api.StopRunningHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.StopRunningHTTPResponse{BaseResp: baseResp})
		return
	}
	resp, err := apicontrol.StopRunning(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.StopRunningHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}
