// Code generated by hertztool.

package handler

import (
	"context"
	"encoding/json"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	aic_agent_sdk_api "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/hertz_gen/aic_agent_sdk_api"
	apiinput "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/service/input"
)

// SubmitInput .
// @router /ad/aic_agent_sdk/submit_input [POST]
func SubmitInput(ctx context.Context, c *app.RequestContext) {
	var req aic_agent_sdk_api.SubmitInputHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.SubmitInputHTTPResponse{BaseResp: baseResp})
		return
	}
	if interrupt := submitInputInterrupt(c.Request.Body()); interrupt != nil {
		ctx = apiinput.ContextWithResumeInterrupt(ctx, interrupt)
	}
	resp, err := apiinput.Submit(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.SubmitInputHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}

func submitInputInterrupt(body []byte) *apiinput.ResumeInterruptInput {
	var raw struct {
		Interrupt *apiinput.ResumeInterruptInput `json:"interrupt"`
	}
	if len(body) == 0 || json.Unmarshal(body, &raw) != nil {
		return nil
	}
	return raw.Interrupt
}
