// Code generated by hertztool.

package handler

import (
	"context"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	aic_agent_sdk_api "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/hertz_gen/aic_agent_sdk_api"
	apisession "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/service/session"
)

// UpdateSession .
// @router /ad/aic_agent_sdk/update_session [POST]
func UpdateSession(ctx context.Context, c *app.RequestContext) {
	var req aic_agent_sdk_api.UpdateSessionHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.UpdateSessionHTTPResponse{BaseResp: baseResp})
		return
	}
	resp, err := apisession.Update(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &aic_agent_sdk_api.UpdateSessionHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}
