// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/wd/go/src/github.com/cloudwego/eino/components/tool/interface.go
//
// Generated by this command:
//
//	mockgen -source=/Users/wd/go/src/github.com/cloudwego/eino/components/tool/interface.go -destination=mock/mock_tool/mock_tool.go
//

// Package mock_tool is a generated GoMock package.
package mock_tool

import (
	context "context"
	reflect "reflect"

	tool "github.com/cloudwego/eino/components/tool"
	schema "github.com/cloudwego/eino/schema"
	gomock "go.uber.org/mock/gomock"
)

// MockBaseTool is a mock of BaseTool interface.
type MockBaseTool struct {
	ctrl     *gomock.Controller
	recorder *MockBaseToolMockRecorder
	isgomock struct{}
}

// MockBaseToolMockRecorder is the mock recorder for MockBaseTool.
type MockBaseToolMockRecorder struct {
	mock *MockBaseTool
}

// NewMockBaseTool creates a new mock instance.
func NewMockBaseTool(ctrl *gomock.Controller) *MockBaseTool {
	mock := &MockBaseTool{ctrl: ctrl}
	mock.recorder = &MockBaseToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseTool) EXPECT() *MockBaseToolMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockBaseTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx)
	ret0, _ := ret[0].(*schema.ToolInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockBaseToolMockRecorder) Info(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockBaseTool)(nil).Info), ctx)
}

// MockInvokableTool is a mock of InvokableTool interface.
type MockInvokableTool struct {
	ctrl     *gomock.Controller
	recorder *MockInvokableToolMockRecorder
	isgomock struct{}
}

// MockInvokableToolMockRecorder is the mock recorder for MockInvokableTool.
type MockInvokableToolMockRecorder struct {
	mock *MockInvokableTool
}

// NewMockInvokableTool creates a new mock instance.
func NewMockInvokableTool(ctrl *gomock.Controller) *MockInvokableTool {
	mock := &MockInvokableTool{ctrl: ctrl}
	mock.recorder = &MockInvokableToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvokableTool) EXPECT() *MockInvokableToolMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockInvokableTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx)
	ret0, _ := ret[0].(*schema.ToolInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockInvokableToolMockRecorder) Info(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockInvokableTool)(nil).Info), ctx)
}

// InvokableRun mocks base method.
func (m *MockInvokableTool) InvokableRun(ctx context.Context, argumentsInJSON string, opts ...tool.Option) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, argumentsInJSON}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvokableRun", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvokableRun indicates an expected call of InvokableRun.
func (mr *MockInvokableToolMockRecorder) InvokableRun(ctx, argumentsInJSON any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, argumentsInJSON}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokableRun", reflect.TypeOf((*MockInvokableTool)(nil).InvokableRun), varargs...)
}

// MockStreamableTool is a mock of StreamableTool interface.
type MockStreamableTool struct {
	ctrl     *gomock.Controller
	recorder *MockStreamableToolMockRecorder
	isgomock struct{}
}

// MockStreamableToolMockRecorder is the mock recorder for MockStreamableTool.
type MockStreamableToolMockRecorder struct {
	mock *MockStreamableTool
}

// NewMockStreamableTool creates a new mock instance.
func NewMockStreamableTool(ctrl *gomock.Controller) *MockStreamableTool {
	mock := &MockStreamableTool{ctrl: ctrl}
	mock.recorder = &MockStreamableToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamableTool) EXPECT() *MockStreamableToolMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockStreamableTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx)
	ret0, _ := ret[0].(*schema.ToolInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockStreamableToolMockRecorder) Info(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockStreamableTool)(nil).Info), ctx)
}

// StreamableRun mocks base method.
func (m *MockStreamableTool) StreamableRun(ctx context.Context, argumentsInJSON string, opts ...tool.Option) (*schema.StreamReader[string], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, argumentsInJSON}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamableRun", varargs...)
	ret0, _ := ret[0].(*schema.StreamReader[string])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamableRun indicates an expected call of StreamableRun.
func (mr *MockStreamableToolMockRecorder) StreamableRun(ctx, argumentsInJSON any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, argumentsInJSON}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamableRun", reflect.TypeOf((*MockStreamableTool)(nil).StreamableRun), varargs...)
}

// MockEnhancedInvokableTool is a mock of EnhancedInvokableTool interface.
type MockEnhancedInvokableTool struct {
	ctrl     *gomock.Controller
	recorder *MockEnhancedInvokableToolMockRecorder
	isgomock struct{}
}

// MockEnhancedInvokableToolMockRecorder is the mock recorder for MockEnhancedInvokableTool.
type MockEnhancedInvokableToolMockRecorder struct {
	mock *MockEnhancedInvokableTool
}

// NewMockEnhancedInvokableTool creates a new mock instance.
func NewMockEnhancedInvokableTool(ctrl *gomock.Controller) *MockEnhancedInvokableTool {
	mock := &MockEnhancedInvokableTool{ctrl: ctrl}
	mock.recorder = &MockEnhancedInvokableToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnhancedInvokableTool) EXPECT() *MockEnhancedInvokableToolMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockEnhancedInvokableTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx)
	ret0, _ := ret[0].(*schema.ToolInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockEnhancedInvokableToolMockRecorder) Info(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockEnhancedInvokableTool)(nil).Info), ctx)
}

// InvokableRun mocks base method.
func (m *MockEnhancedInvokableTool) InvokableRun(ctx context.Context, toolArgument *schema.ToolArgument, opts ...tool.Option) (*schema.ToolResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, toolArgument}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvokableRun", varargs...)
	ret0, _ := ret[0].(*schema.ToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InvokableRun indicates an expected call of InvokableRun.
func (mr *MockEnhancedInvokableToolMockRecorder) InvokableRun(ctx, toolArgument any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, toolArgument}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvokableRun", reflect.TypeOf((*MockEnhancedInvokableTool)(nil).InvokableRun), varargs...)
}

// MockEnhancedStreamableTool is a mock of EnhancedStreamableTool interface.
type MockEnhancedStreamableTool struct {
	ctrl     *gomock.Controller
	recorder *MockEnhancedStreamableToolMockRecorder
	isgomock struct{}
}

// MockEnhancedStreamableToolMockRecorder is the mock recorder for MockEnhancedStreamableTool.
type MockEnhancedStreamableToolMockRecorder struct {
	mock *MockEnhancedStreamableTool
}

// NewMockEnhancedStreamableTool creates a new mock instance.
func NewMockEnhancedStreamableTool(ctrl *gomock.Controller) *MockEnhancedStreamableTool {
	mock := &MockEnhancedStreamableTool{ctrl: ctrl}
	mock.recorder = &MockEnhancedStreamableToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnhancedStreamableTool) EXPECT() *MockEnhancedStreamableToolMockRecorder {
	return m.recorder
}

// Info mocks base method.
func (m *MockEnhancedStreamableTool) Info(ctx context.Context) (*schema.ToolInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info", ctx)
	ret0, _ := ret[0].(*schema.ToolInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Info indicates an expected call of Info.
func (mr *MockEnhancedStreamableToolMockRecorder) Info(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockEnhancedStreamableTool)(nil).Info), ctx)
}

// StreamableRun mocks base method.
func (m *MockEnhancedStreamableTool) StreamableRun(ctx context.Context, toolArgument *schema.ToolArgument, opts ...tool.Option) (*schema.StreamReader[*schema.ToolResult], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, toolArgument}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamableRun", varargs...)
	ret0, _ := ret[0].(*schema.StreamReader[*schema.ToolResult])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamableRun indicates an expected call of StreamableRun.
func (mr *MockEnhancedStreamableToolMockRecorder) StreamableRun(ctx, toolArgument any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, toolArgument}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamableRun", reflect.TypeOf((*MockEnhancedStreamableTool)(nil).StreamableRun), varargs...)
}
