// Code generated by hertztool. DO NOT EDIT.

package router

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	deep_agent_sdk "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/biz/router/deep_agent_sdk"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	deep_agent_sdk.Register(r)
}
