// Code generated by Kitex v1.22.1. DO NOT EDIT.

package aicagentsdksessionservice

import (
	"context"
	aic_agent_sdk_session "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_session/kitex_gen/aic_agent_sdk_session"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateSession": kitex.NewMethodInfo(
		createSessionHandler,
		newAICAgentSDKSessionServiceCreateSessionArgs,
		newAICAgentSDKSessionServiceCreateSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListSessions": kitex.NewMethodInfo(
		listSessionsHandler,
		newAICAgentSDKSessionServiceListSessionsArgs,
		newAICAgentSDKSessionServiceListSessionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSession": kitex.NewMethodInfo(
		getSessionHandler,
		newAICAgentSDKSessionServiceGetSessionArgs,
		newAICAgentSDKSessionServiceGetSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateSession": kitex.NewMethodInfo(
		updateSessionHandler,
		newAICAgentSDKSessionServiceUpdateSessionArgs,
		newAICAgentSDKSessionServiceUpdateSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CloseSession": kitex.NewMethodInfo(
		closeSessionHandler,
		newAICAgentSDKSessionServiceCloseSessionArgs,
		newAICAgentSDKSessionServiceCloseSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CloseProject": kitex.NewMethodInfo(
		closeProjectHandler,
		newAICAgentSDKSessionServiceCloseProjectArgs,
		newAICAgentSDKSessionServiceCloseProjectResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BindMainThread": kitex.NewMethodInfo(
		bindMainThreadHandler,
		newAICAgentSDKSessionServiceBindMainThreadArgs,
		newAICAgentSDKSessionServiceBindMainThreadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"TouchSession": kitex.NewMethodInfo(
		touchSessionHandler,
		newAICAgentSDKSessionServiceTouchSessionArgs,
		newAICAgentSDKSessionServiceTouchSessionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListProjects": kitex.NewMethodInfo(
		listProjectsHandler,
		newAICAgentSDKSessionServiceListProjectsArgs,
		newAICAgentSDKSessionServiceListProjectsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aICAgentSDKSessionServiceServiceInfo                = NewServiceInfo()
	aICAgentSDKSessionServiceServiceInfoForClient       = NewServiceInfoForClient()
	aICAgentSDKSessionServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aICAgentSDKSessionServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aICAgentSDKSessionServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aICAgentSDKSessionServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AICAgentSDKSessionService"
	handlerType := (*aic_agent_sdk_session.AICAgentSDKSessionService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "aic_agent_sdk_session",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.22.1",
		Extra:           extra,
	}
	return svcInfo
}

func createSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceCreateSessionArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceCreateSessionResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).CreateSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceCreateSessionArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceCreateSessionArgs()
}

func newAICAgentSDKSessionServiceCreateSessionResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceCreateSessionResult()
}

func listSessionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceListSessionsArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceListSessionsResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).ListSessions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceListSessionsArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceListSessionsArgs()
}

func newAICAgentSDKSessionServiceListSessionsResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceListSessionsResult()
}

func getSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceGetSessionArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceGetSessionResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).GetSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceGetSessionArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceGetSessionArgs()
}

func newAICAgentSDKSessionServiceGetSessionResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceGetSessionResult()
}

func updateSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceUpdateSessionArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceUpdateSessionResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).UpdateSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceUpdateSessionArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceUpdateSessionArgs()
}

func newAICAgentSDKSessionServiceUpdateSessionResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceUpdateSessionResult()
}

func closeSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceCloseSessionArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceCloseSessionResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).CloseSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceCloseSessionArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceCloseSessionArgs()
}

func newAICAgentSDKSessionServiceCloseSessionResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceCloseSessionResult()
}

func closeProjectHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceCloseProjectArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceCloseProjectResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).CloseProject(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceCloseProjectArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceCloseProjectArgs()
}

func newAICAgentSDKSessionServiceCloseProjectResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceCloseProjectResult()
}

func bindMainThreadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceBindMainThreadArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceBindMainThreadResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).BindMainThread(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceBindMainThreadArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceBindMainThreadArgs()
}

func newAICAgentSDKSessionServiceBindMainThreadResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceBindMainThreadResult()
}

func touchSessionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceTouchSessionArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceTouchSessionResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).TouchSession(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceTouchSessionArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceTouchSessionArgs()
}

func newAICAgentSDKSessionServiceTouchSessionResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceTouchSessionResult()
}

func listProjectsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*aic_agent_sdk_session.AICAgentSDKSessionServiceListProjectsArgs)
	realResult := result.(*aic_agent_sdk_session.AICAgentSDKSessionServiceListProjectsResult)
	success, err := handler.(aic_agent_sdk_session.AICAgentSDKSessionService).ListProjects(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAICAgentSDKSessionServiceListProjectsArgs() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceListProjectsArgs()
}

func newAICAgentSDKSessionServiceListProjectsResult() interface{} {
	return aic_agent_sdk_session.NewAICAgentSDKSessionServiceListProjectsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateSession(ctx context.Context, req *aic_agent_sdk_session.CreateSessionRequest) (r *aic_agent_sdk_session.CreateSessionResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceCreateSessionArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceCreateSessionResult
	if err = p.c.Call(ctx, "CreateSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListSessions(ctx context.Context, req *aic_agent_sdk_session.ListSessionsRequest) (r *aic_agent_sdk_session.ListSessionsResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceListSessionsArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceListSessionsResult
	if err = p.c.Call(ctx, "ListSessions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSession(ctx context.Context, req *aic_agent_sdk_session.GetSessionRequest) (r *aic_agent_sdk_session.GetSessionResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceGetSessionArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceGetSessionResult
	if err = p.c.Call(ctx, "GetSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateSession(ctx context.Context, req *aic_agent_sdk_session.UpdateSessionRequest) (r *aic_agent_sdk_session.UpdateSessionResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceUpdateSessionArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceUpdateSessionResult
	if err = p.c.Call(ctx, "UpdateSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CloseSession(ctx context.Context, req *aic_agent_sdk_session.CloseSessionRequest) (r *aic_agent_sdk_session.CloseSessionResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceCloseSessionArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceCloseSessionResult
	if err = p.c.Call(ctx, "CloseSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CloseProject(ctx context.Context, req *aic_agent_sdk_session.CloseProjectRequest) (r *aic_agent_sdk_session.CloseProjectResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceCloseProjectArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceCloseProjectResult
	if err = p.c.Call(ctx, "CloseProject", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BindMainThread(ctx context.Context, req *aic_agent_sdk_session.BindMainThreadRequest) (r *aic_agent_sdk_session.BindMainThreadResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceBindMainThreadArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceBindMainThreadResult
	if err = p.c.Call(ctx, "BindMainThread", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) TouchSession(ctx context.Context, req *aic_agent_sdk_session.TouchSessionRequest) (r *aic_agent_sdk_session.TouchSessionResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceTouchSessionArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceTouchSessionResult
	if err = p.c.Call(ctx, "TouchSession", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListProjects(ctx context.Context, req *aic_agent_sdk_session.ListProjectsRequest) (r *aic_agent_sdk_session.ListProjectsResponse, err error) {
	var _args aic_agent_sdk_session.AICAgentSDKSessionServiceListProjectsArgs
	_args.Req = req
	var _result aic_agent_sdk_session.AICAgentSDKSessionServiceListProjectsResult
	if err = p.c.Call(ctx, "ListProjects", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
