// Code generated by Kitex v1.22.1. DO NOT EDIT.

package aicagentsdksessionservice

import (
	byted "code.byted.org/kite/kitex/byted"
	"context"
	aic_agent_sdk_session "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_session/kitex_gen/aic_agent_sdk_session"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateSession(ctx context.Context, req *aic_agent_sdk_session.CreateSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.CreateSessionResponse, err error)
	ListSessions(ctx context.Context, req *aic_agent_sdk_session.ListSessionsRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.ListSessionsResponse, err error)
	GetSession(ctx context.Context, req *aic_agent_sdk_session.GetSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.GetSessionResponse, err error)
	UpdateSession(ctx context.Context, req *aic_agent_sdk_session.UpdateSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.UpdateSessionResponse, err error)
	CloseSession(ctx context.Context, req *aic_agent_sdk_session.CloseSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.CloseSessionResponse, err error)
	CloseProject(ctx context.Context, req *aic_agent_sdk_session.CloseProjectRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.CloseProjectResponse, err error)
	BindMainThread(ctx context.Context, req *aic_agent_sdk_session.BindMainThreadRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.BindMainThreadResponse, err error)
	TouchSession(ctx context.Context, req *aic_agent_sdk_session.TouchSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.TouchSessionResponse, err error)
	ListProjects(ctx context.Context, req *aic_agent_sdk_session.ListProjectsRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.ListProjectsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	config := byted.NewClientConfig()
	config.DestService = destService
	options = append(options, byted.ClientSuiteWithConfig(serviceInfo(), config))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAICAgentSDKSessionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAICAgentSDKSessionServiceClient struct {
	*kClient
}

func (p *kAICAgentSDKSessionServiceClient) CreateSession(ctx context.Context, req *aic_agent_sdk_session.CreateSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.CreateSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateSession(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) ListSessions(ctx context.Context, req *aic_agent_sdk_session.ListSessionsRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.ListSessionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListSessions(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) GetSession(ctx context.Context, req *aic_agent_sdk_session.GetSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.GetSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSession(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) UpdateSession(ctx context.Context, req *aic_agent_sdk_session.UpdateSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.UpdateSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateSession(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) CloseSession(ctx context.Context, req *aic_agent_sdk_session.CloseSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.CloseSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseSession(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) CloseProject(ctx context.Context, req *aic_agent_sdk_session.CloseProjectRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.CloseProjectResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseProject(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) BindMainThread(ctx context.Context, req *aic_agent_sdk_session.BindMainThreadRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.BindMainThreadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BindMainThread(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) TouchSession(ctx context.Context, req *aic_agent_sdk_session.TouchSessionRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.TouchSessionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.TouchSession(ctx, req)
}

func (p *kAICAgentSDKSessionServiceClient) ListProjects(ctx context.Context, req *aic_agent_sdk_session.ListProjectsRequest, callOptions ...callopt.Option) (r *aic_agent_sdk_session.ListProjectsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListProjects(ctx, req)
}

// NewClientWithBytedConfig creates a client for the service defined in IDL.
func NewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) (Client, error) {
	if config == nil {
		config = byted.NewClientConfig()
	}
	config.DestService = destService

	var options []client.Option
	options = append(options, client.WithDestService(destService))

	clientServiceInfo := serviceInfoForClient()
	options = append(options, byted.ClientSuiteWithConfig(clientServiceInfo, config))
	options = append(options, opts...)
	kc, err := client.NewClient(clientServiceInfo, options...)
	if err != nil {
		return nil, err
	}
	return &kAICAgentSDKSessionServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClientWithBytedConfig creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) Client {
	kc, err := NewClientWithBytedConfig(destService, config, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}
