// Code generated by COMMENTS_BUILD_TOOLS 2.0.89. DO NOT EDIT.
package model

import (
	"time"
)

func (TMemoryStage2Job) TableName() string {
	return "t_memory_stage2_job"
}

func NewTMemoryStage2Job() *TMemoryStage2Job {
	return &TMemoryStage2Job{}
}

type TMemoryStage2Job struct {
	Id                   int64      `gorm:"column:id;primary_key" json:"id"`                             // database row id generated by caller-provided id generator
	LastSuccessAt        *time.Time `gorm:"column:last_success_at" json:"last_success_at"`               // last successful stage2 completion time
	LeaseUntil           *time.Time `gorm:"column:lease_until" json:"lease_until"`                       // stage2 lease expiry
	RetryAt              *time.Time `gorm:"column:retry_at" json:"retry_at"`                             // earliest retry time after failed stage2
	UpdatedAt            *time.Time `gorm:"column:updated_at" json:"updated_at"`                         // row update time
	UserId               string     `gorm:"column:user_id" json:"user_id"`                               // memory owner user id
	Status               string     `gorm:"column:status" json:"status"`                                 // stage2 job status
	InputWatermark       string     `gorm:"column:input_watermark" json:"input_watermark"`               // latest pending stage1 input watermark
	LastSuccessWatermark string     `gorm:"column:last_success_watermark" json:"last_success_watermark"` // stage1 input watermark completed by last successful stage2
	Stage2ThreadId       string     `gorm:"column:stage2_thread_id" json:"stage2_thread_id"`             // bound memory_consolidation thread id
	LeaseOwner           string     `gorm:"column:lease_owner" json:"lease_owner"`                       // stage2 lease owner
	OwnershipToken       string     `gorm:"column:ownership_token" json:"ownership_token"`               // stage2 lease token
	LastError            string     `gorm:"column:last_error" json:"last_error"`                         // latest stage2 error summary
}
