// Code generated by COMMENTS_BUILD_TOOLS 2.0.89. DO NOT EDIT.
package model

import (
	"time"
)

func (TMemoryStage1Output) TableName() string {
	return "t_memory_stage1_output"
}

func NewTMemoryStage1Output() *TMemoryStage1Output {
	return &TMemoryStage1Output{}
}

type TMemoryStage1Output struct {
	UsageCount      int        `gorm:"column:usage_count" json:"usage_count"`             // future memory usage count
	Id              int64      `gorm:"column:id;primary_key" json:"id"`                   // database row id generated by caller-provided id generator
	GeneratedAt     *time.Time `gorm:"column:generated_at" json:"generated_at"`           // stage1 generation time
	SourceUpdatedAt *time.Time `gorm:"column:source_updated_at" json:"source_updated_at"` // source history watermark used by this output
	LastUsedAt      *time.Time `gorm:"column:last_used_at" json:"last_used_at"`           // future memory usage update time
	Stage1Key       string     `gorm:"column:stage1_key" json:"stage1_key"`               // stable logical stage1 output key
	UserId          string     `gorm:"column:user_id" json:"user_id"`                     // memory owner user id
	SourceThreadId  string     `gorm:"column:source_thread_id" json:"source_thread_id"`   // source Agent Coordinator thread id
	SourceTurnID    string     `gorm:"column:source_turn_id" json:"source_turn_id"`       // source turn id when available
	RawMemory       string     `gorm:"column:raw_memory" json:"raw_memory"`               // stage1 raw memory extracted from source history
	RolloutSummary  string     `gorm:"column:rollout_summary" json:"rollout_summary"`     // stage1 source rollout summary
	Status          string     `gorm:"column:status" json:"status"`                       // stage1 output status
	ErrorSummary    string     `gorm:"column:error_summary" json:"error_summary"`         // stage1 extraction error summary
}
