// Code generated by COMMENTS_BUILD_TOOLS 2.0.89. DO NOT EDIT.
package model

import (
	"time"
)

func (TMemorySource) TableName() string {
	return "t_memory_source"
}

func NewTMemorySource() *TMemorySource {
	return &TMemorySource{}
}

type TMemorySource struct {
	Attempts                         int        `gorm:"column:attempts" json:"attempts"`                                                           // stage1 claim attempts
	Id                               int64      `gorm:"column:id;primary_key" json:"id"`                                                           // database row id generated by caller-provided id generator
	SourceUpdatedAt                  *time.Time `gorm:"column:source_updated_at" json:"source_updated_at"`                                         // latest source thread update time used for stage1 eligibility
	EligibleAt                       *time.Time `gorm:"column:eligible_at" json:"eligible_at"`                                                     // earliest time this source may be claimed by stage1
	LastStage1SuccessSourceUpdatedAt *time.Time `gorm:"column:last_stage1_success_source_updated_at" json:"last_stage1_success_source_updated_at"` // source watermark processed by last successful stage1
	LeaseUntil                       *time.Time `gorm:"column:lease_until" json:"lease_until"`                                                     // stage1 lease expiry
	UpdatedAt                        *time.Time `gorm:"column:updated_at" json:"updated_at"`                                                       // row update time
	UserId                           string     `gorm:"column:user_id" json:"user_id"`                                                             // memory owner user id
	SourceThreadId                   string     `gorm:"column:source_thread_id" json:"source_thread_id"`                                           // source Agent Coordinator thread id
	Mode                             string     `gorm:"column:mode" json:"mode"`                                                                   // source memory mode: enabled disabled polluted
	Status                           string     `gorm:"column:status" json:"status"`                                                               // stage1 source status
	Owner                            string     `gorm:"column:owner" json:"owner"`                                                                 // stage1 lease owner
	OwnershipToken                   string     `gorm:"column:ownership_token" json:"ownership_token"`                                             // stage1 lease token
	LastStage1OutputKey              string     `gorm:"column:last_stage1_output_key" json:"last_stage1_output_key"`                               // last logical stage1 output key
	ErrorSummary                     string     `gorm:"column:error_summary" json:"error_summary"`                                                 // latest stage1 error summary
}
