// Code generated by COMMENTS_BUILD_TOOLS 2.0.89. DO NOT EDIT.
package model

import (
	"time"
)

func (TMemoryBaseline) TableName() string {
	return "t_memory_baseline"
}

func NewTMemoryBaseline() *TMemoryBaseline {
	return &TMemoryBaseline{}
}

type TMemoryBaseline struct {
	Id        int64      `gorm:"column:id;primary_key" json:"id"`     // database row id generated by caller-provided id generator
	UpdatedAt *time.Time `gorm:"column:updated_at" json:"updated_at"` // baseline update time
	UserId    string     `gorm:"column:user_id" json:"user_id"`       // memory owner user id
	Hash      string     `gorm:"column:hash" json:"hash"`             // last successful memory workspace input baseline hash
}
