// Code generated by hertztool.

package main

import (
	"code.byted.org/middleware/hertz/byted"
	"code.byted.org/middleware/hertz/pkg/app/server"
)

func main() {
	byted.Init()
	r := newServer()

	register(r)
	r.Spin()
}

func newServer() *server.Hertz {
	return byted.Default(server.WithSenseClientDisconnection(true))
}
