// Code generated by hertztool. DO NOT EDIT.

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	router "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/biz/router"
)

// register registers all routers.
func register(r *server.Hertz) {

	router.GeneratedRegister(r)

	customizedRegister(r)

}
