// Code generated by hertztool

package main

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	handler "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/biz/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.POST("/ad/aic_agent_sdk/ping", handler.Ping)
	r.GET("/", handler.WebApp)
	r.GET("/static/*filepath", handler.WebAsset)
	r.GET("/styles.css", handler.WebRootAsset)
	r.GET("/app.js", handler.WebRootAsset)
	r.GET("/api.js", handler.WebRootAsset)
	r.GET("/render.js", handler.WebRootAsset)
	r.GET("/state.js", handler.WebRootAsset)
	r.GET("/stream_controller.js", handler.WebRootAsset)
	r.GET("/submit_gate.js", handler.WebRootAsset)
	r.GET("/timeline_model.js", handler.WebRootAsset)
	r.GET("/favicon.svg", handler.WebRootAsset)
	r.GET("/favicon.ico", handler.Favicon)
	r.POST("/ad/aic_agent_sdk/list_projects", handler.ListProjects)
	r.POST("/ad/aic_agent_sdk/close_project", handler.CloseProject)
	r.POST("/ad/aic_agent_sdk/list_files", handler.ListFiles)
	r.GET("/ad/aic_agent_sdk/file", handler.ServeFile)

	// your code ...
}
