// Code generated by hertz generator.

package deep_agent_sdk

import (
	"code.byted.org/middleware/hertz/pkg/app"
)

func root_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func deep_agent_sdk_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func create_session_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func list_sessions_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func get_session_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func update_session_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func close_session_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func submit_input_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func stop_running_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func list_timeline_mws() []app.HandlerFunc {
	// your code...
	return nil
}

func subscribe_timeline_mws() []app.HandlerFunc {
	// your code...
	return nil
}
