// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package aic_agent_sdk_common

import (
	apache_warning "code.byted.org/middleware/apache_monitor_hertz"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

type AgentSessionStatus int64

const (
	AgentSessionStatus_ACTIVE   AgentSessionStatus = 1
	AgentSessionStatus_ARCHIVED AgentSessionStatus = 2
	AgentSessionStatus_CLOSED   AgentSessionStatus = 3
)

func (p AgentSessionStatus) String() string {
	switch p {
	case AgentSessionStatus_ACTIVE:
		return "ACTIVE"
	case AgentSessionStatus_ARCHIVED:
		return "ARCHIVED"
	case AgentSessionStatus_CLOSED:
		return "CLOSED"
	}
	return "<UNSET>"
}

func AgentSessionStatusFromString(s string) (AgentSessionStatus, error) {
	switch s {
	case "ACTIVE":
		return AgentSessionStatus_ACTIVE, nil
	case "ARCHIVED":
		return AgentSessionStatus_ARCHIVED, nil
	case "CLOSED":
		return AgentSessionStatus_CLOSED, nil
	}
	return AgentSessionStatus(0), fmt.Errorf("not a valid AgentSessionStatus string")
}

func AgentSessionStatusPtr(v AgentSessionStatus) *AgentSessionStatus { return &v }
func (p *AgentSessionStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AgentSessionStatus(result.Int64)
	return
}

func (p *AgentSessionStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AgentThreadStatus int64

const (
	AgentThreadStatus_IDLE    AgentThreadStatus = 1
	AgentThreadStatus_READY   AgentThreadStatus = 2
	AgentThreadStatus_RUNNING AgentThreadStatus = 3
	AgentThreadStatus_BLOCKED AgentThreadStatus = 4
	AgentThreadStatus_CLOSING AgentThreadStatus = 5
	AgentThreadStatus_CLOSED  AgentThreadStatus = 6
)

func (p AgentThreadStatus) String() string {
	switch p {
	case AgentThreadStatus_IDLE:
		return "IDLE"
	case AgentThreadStatus_READY:
		return "READY"
	case AgentThreadStatus_RUNNING:
		return "RUNNING"
	case AgentThreadStatus_BLOCKED:
		return "BLOCKED"
	case AgentThreadStatus_CLOSING:
		return "CLOSING"
	case AgentThreadStatus_CLOSED:
		return "CLOSED"
	}
	return "<UNSET>"
}

func AgentThreadStatusFromString(s string) (AgentThreadStatus, error) {
	switch s {
	case "IDLE":
		return AgentThreadStatus_IDLE, nil
	case "READY":
		return AgentThreadStatus_READY, nil
	case "RUNNING":
		return AgentThreadStatus_RUNNING, nil
	case "BLOCKED":
		return AgentThreadStatus_BLOCKED, nil
	case "CLOSING":
		return AgentThreadStatus_CLOSING, nil
	case "CLOSED":
		return AgentThreadStatus_CLOSED, nil
	}
	return AgentThreadStatus(0), fmt.Errorf("not a valid AgentThreadStatus string")
}

func AgentThreadStatusPtr(v AgentThreadStatus) *AgentThreadStatus { return &v }
func (p *AgentThreadStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AgentThreadStatus(result.Int64)
	return
}

func (p *AgentThreadStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AgentThreadRole int64

const (
	AgentThreadRole_MAIN  AgentThreadRole = 1
	AgentThreadRole_CHILD AgentThreadRole = 2
)

func (p AgentThreadRole) String() string {
	switch p {
	case AgentThreadRole_MAIN:
		return "MAIN"
	case AgentThreadRole_CHILD:
		return "CHILD"
	}
	return "<UNSET>"
}

func AgentThreadRoleFromString(s string) (AgentThreadRole, error) {
	switch s {
	case "MAIN":
		return AgentThreadRole_MAIN, nil
	case "CHILD":
		return AgentThreadRole_CHILD, nil
	}
	return AgentThreadRole(0), fmt.Errorf("not a valid AgentThreadRole string")
}

func AgentThreadRolePtr(v AgentThreadRole) *AgentThreadRole { return &v }
func (p *AgentThreadRole) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = AgentThreadRole(result.Int64)
	return
}

func (p *AgentThreadRole) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type InputMode int64

const (
	InputMode_IMPL_PLAN       InputMode = 1
	InputMode_COMPACT_CONTEXT InputMode = 2
)

func (p InputMode) String() string {
	switch p {
	case InputMode_IMPL_PLAN:
		return "IMPL_PLAN"
	case InputMode_COMPACT_CONTEXT:
		return "COMPACT_CONTEXT"
	}
	return "<UNSET>"
}

func InputModeFromString(s string) (InputMode, error) {
	switch s {
	case "IMPL_PLAN":
		return InputMode_IMPL_PLAN, nil
	case "COMPACT_CONTEXT":
		return InputMode_COMPACT_CONTEXT, nil
	}
	return InputMode(0), fmt.Errorf("not a valid InputMode string")
}

func InputModePtr(v InputMode) *InputMode { return &v }
func (p *InputMode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = InputMode(result.Int64)
	return
}

func (p *InputMode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AgentSession struct {
	SessionID          int64              `thrift:"session_id,1" json:"session_id,string" form:"session_id" query:"session_id"`
	UID                int64              `thrift:"uid,2" json:"uid,string" form:"uid" query:"uid"`
	Title              *string            `thrift:"title,5,optional" form:"title" json:"title,omitempty" query:"title"`
	MainThreadID       *int64             `thrift:"main_thread_id,6,optional" json:"main_thread_id,string,omitempty" form:"main_thread_id" query:"main_thread_id"`
	ProjectName        *string            `thrift:"project_name,7,optional" form:"project_name" json:"project_name,omitempty" query:"project_name"`
	LastMessagePreview *string            `thrift:"last_message_preview,8,optional" form:"last_message_preview" json:"last_message_preview,omitempty" query:"last_message_preview"`
	LastActiveAtMs     *int64             `thrift:"last_active_at_ms,9,optional" form:"last_active_at_ms" json:"last_active_at_ms,omitempty" query:"last_active_at_ms"`
	Status             AgentSessionStatus `thrift:"status,10" form:"status" json:"status" query:"status"`
	ProjectPath        *string            `thrift:"project_path,11,optional" form:"project_path" json:"project_path,omitempty" query:"project_path"`
	CreatedAtMs        *int64             `thrift:"created_at_ms,12,optional" form:"created_at_ms" json:"created_at_ms,omitempty" query:"created_at_ms"`
	UpdatedAtMs        *int64             `thrift:"updated_at_ms,13,optional" form:"updated_at_ms" json:"updated_at_ms,omitempty" query:"updated_at_ms"`
}

func NewAgentSession() *AgentSession {
	return &AgentSession{}
}

func (p *AgentSession) InitDefault() {
}

func (p *AgentSession) GetSessionID() (v int64) {
	return p.SessionID
}

func (p *AgentSession) GetUID() (v int64) {
	return p.UID
}

var AgentSession_Title_DEFAULT string

func (p *AgentSession) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return AgentSession_Title_DEFAULT
	}
	return *p.Title
}

var AgentSession_MainThreadID_DEFAULT int64

func (p *AgentSession) GetMainThreadID() (v int64) {
	if !p.IsSetMainThreadID() {
		return AgentSession_MainThreadID_DEFAULT
	}
	return *p.MainThreadID
}

var AgentSession_ProjectName_DEFAULT string

func (p *AgentSession) GetProjectName() (v string) {
	if !p.IsSetProjectName() {
		return AgentSession_ProjectName_DEFAULT
	}
	return *p.ProjectName
}

var AgentSession_LastMessagePreview_DEFAULT string

func (p *AgentSession) GetLastMessagePreview() (v string) {
	if !p.IsSetLastMessagePreview() {
		return AgentSession_LastMessagePreview_DEFAULT
	}
	return *p.LastMessagePreview
}

var AgentSession_LastActiveAtMs_DEFAULT int64

func (p *AgentSession) GetLastActiveAtMs() (v int64) {
	if !p.IsSetLastActiveAtMs() {
		return AgentSession_LastActiveAtMs_DEFAULT
	}
	return *p.LastActiveAtMs
}

func (p *AgentSession) GetStatus() (v AgentSessionStatus) {
	return p.Status
}

var AgentSession_ProjectPath_DEFAULT string

func (p *AgentSession) GetProjectPath() (v string) {
	if !p.IsSetProjectPath() {
		return AgentSession_ProjectPath_DEFAULT
	}
	return *p.ProjectPath
}

var AgentSession_CreatedAtMs_DEFAULT int64

func (p *AgentSession) GetCreatedAtMs() (v int64) {
	if !p.IsSetCreatedAtMs() {
		return AgentSession_CreatedAtMs_DEFAULT
	}
	return *p.CreatedAtMs
}

var AgentSession_UpdatedAtMs_DEFAULT int64

func (p *AgentSession) GetUpdatedAtMs() (v int64) {
	if !p.IsSetUpdatedAtMs() {
		return AgentSession_UpdatedAtMs_DEFAULT
	}
	return *p.UpdatedAtMs
}

var fieldIDToName_AgentSession = map[int16]string{
	1:  "session_id",
	2:  "uid",
	5:  "title",
	6:  "main_thread_id",
	7:  "project_name",
	8:  "last_message_preview",
	9:  "last_active_at_ms",
	10: "status",
	11: "project_path",
	12: "created_at_ms",
	13: "updated_at_ms",
}

func (p *AgentSession) IsSetTitle() bool {
	return p.Title != nil
}

func (p *AgentSession) IsSetMainThreadID() bool {
	return p.MainThreadID != nil
}

func (p *AgentSession) IsSetProjectName() bool {
	return p.ProjectName != nil
}

func (p *AgentSession) IsSetLastMessagePreview() bool {
	return p.LastMessagePreview != nil
}

func (p *AgentSession) IsSetLastActiveAtMs() bool {
	return p.LastActiveAtMs != nil
}

func (p *AgentSession) IsSetProjectPath() bool {
	return p.ProjectPath != nil
}

func (p *AgentSession) IsSetCreatedAtMs() bool {
	return p.CreatedAtMs != nil
}

func (p *AgentSession) IsSetUpdatedAtMs() bool {
	return p.UpdatedAtMs != nil
}

func (p *AgentSession) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("AgentSession")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 9:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField9(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 10:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField10(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 11:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField11(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 12:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField12(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 13:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField13(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_AgentSession[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *AgentSession) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.SessionID = _field
	return nil
}
func (p *AgentSession) ReadField2(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.UID = _field
	return nil
}
func (p *AgentSession) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Title = _field
	return nil
}
func (p *AgentSession) ReadField6(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.MainThreadID = _field
	return nil
}
func (p *AgentSession) ReadField7(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ProjectName = _field
	return nil
}
func (p *AgentSession) ReadField8(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.LastMessagePreview = _field
	return nil
}
func (p *AgentSession) ReadField9(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.LastActiveAtMs = _field
	return nil
}
func (p *AgentSession) ReadField10(iprot thrift.TProtocol) error {

	var _field AgentSessionStatus
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = AgentSessionStatus(v)
	}
	p.Status = _field
	return nil
}
func (p *AgentSession) ReadField11(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ProjectPath = _field
	return nil
}
func (p *AgentSession) ReadField12(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.CreatedAtMs = _field
	return nil
}
func (p *AgentSession) ReadField13(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UpdatedAtMs = _field
	return nil
}

func (p *AgentSession) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("AgentSession")

	var fieldId int16
	if err = oprot.WriteStructBegin("AgentSession"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
		if err = p.writeField9(oprot); err != nil {
			fieldId = 9
			goto WriteFieldError
		}
		if err = p.writeField10(oprot); err != nil {
			fieldId = 10
			goto WriteFieldError
		}
		if err = p.writeField11(oprot); err != nil {
			fieldId = 11
			goto WriteFieldError
		}
		if err = p.writeField12(oprot); err != nil {
			fieldId = 12
			goto WriteFieldError
		}
		if err = p.writeField13(oprot); err != nil {
			fieldId = 13
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *AgentSession) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("session_id", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.SessionID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *AgentSession) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("uid", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.UID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *AgentSession) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetTitle() {
		if err = oprot.WriteFieldBegin("title", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Title); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}
func (p *AgentSession) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetMainThreadID() {
		if err = oprot.WriteFieldBegin("main_thread_id", thrift.I64, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.MainThreadID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}
func (p *AgentSession) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetProjectName() {
		if err = oprot.WriteFieldBegin("project_name", thrift.STRING, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ProjectName); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}
func (p *AgentSession) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastMessagePreview() {
		if err = oprot.WriteFieldBegin("last_message_preview", thrift.STRING, 8); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.LastMessagePreview); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}
func (p *AgentSession) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastActiveAtMs() {
		if err = oprot.WriteFieldBegin("last_active_at_ms", thrift.I64, 9); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.LastActiveAtMs); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 end error: ", p), err)
}
func (p *AgentSession) writeField10(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("status", thrift.I32, 10); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(int32(p.Status)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 end error: ", p), err)
}
func (p *AgentSession) writeField11(oprot thrift.TProtocol) (err error) {
	if p.IsSetProjectPath() {
		if err = oprot.WriteFieldBegin("project_path", thrift.STRING, 11); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ProjectPath); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 end error: ", p), err)
}
func (p *AgentSession) writeField12(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreatedAtMs() {
		if err = oprot.WriteFieldBegin("created_at_ms", thrift.I64, 12); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.CreatedAtMs); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 12 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 12 end error: ", p), err)
}
func (p *AgentSession) writeField13(oprot thrift.TProtocol) (err error) {
	if p.IsSetUpdatedAtMs() {
		if err = oprot.WriteFieldBegin("updated_at_ms", thrift.I64, 13); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.UpdatedAtMs); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 13 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 13 end error: ", p), err)
}

func (p *AgentSession) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentSession(%+v)", *p)

}

// SessionProject 是从 t_agent_session 聚合出的 project 视图。
//
// 它不是独立实体，也不对应 project 表；project 本质只是 session 的工作目录聚合属性。
type SessionProject struct {
	ProjectName    string `thrift:"project_name,1" form:"project_name" json:"project_name" query:"project_name"`
	ProjectPath    string `thrift:"project_path,2" form:"project_path" json:"project_path" query:"project_path"`
	SessionCount   *int64 `thrift:"session_count,3,optional" form:"session_count" json:"session_count,omitempty" query:"session_count"`
	LastActiveAtMs *int64 `thrift:"last_active_at_ms,4,optional" form:"last_active_at_ms" json:"last_active_at_ms,omitempty" query:"last_active_at_ms"`
}

func NewSessionProject() *SessionProject {
	return &SessionProject{}
}

func (p *SessionProject) InitDefault() {
}

func (p *SessionProject) GetProjectName() (v string) {
	return p.ProjectName
}

func (p *SessionProject) GetProjectPath() (v string) {
	return p.ProjectPath
}

var SessionProject_SessionCount_DEFAULT int64

func (p *SessionProject) GetSessionCount() (v int64) {
	if !p.IsSetSessionCount() {
		return SessionProject_SessionCount_DEFAULT
	}
	return *p.SessionCount
}

var SessionProject_LastActiveAtMs_DEFAULT int64

func (p *SessionProject) GetLastActiveAtMs() (v int64) {
	if !p.IsSetLastActiveAtMs() {
		return SessionProject_LastActiveAtMs_DEFAULT
	}
	return *p.LastActiveAtMs
}

var fieldIDToName_SessionProject = map[int16]string{
	1: "project_name",
	2: "project_path",
	3: "session_count",
	4: "last_active_at_ms",
}

func (p *SessionProject) IsSetSessionCount() bool {
	return p.SessionCount != nil
}

func (p *SessionProject) IsSetLastActiveAtMs() bool {
	return p.LastActiveAtMs != nil
}

func (p *SessionProject) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("SessionProject")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_SessionProject[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *SessionProject) ReadField1(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.ProjectName = _field
	return nil
}
func (p *SessionProject) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.ProjectPath = _field
	return nil
}
func (p *SessionProject) ReadField3(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.SessionCount = _field
	return nil
}
func (p *SessionProject) ReadField4(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.LastActiveAtMs = _field
	return nil
}

func (p *SessionProject) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("SessionProject")

	var fieldId int16
	if err = oprot.WriteStructBegin("SessionProject"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *SessionProject) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("project_name", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.ProjectName); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *SessionProject) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("project_path", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.ProjectPath); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *SessionProject) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetSessionCount() {
		if err = oprot.WriteFieldBegin("session_count", thrift.I64, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.SessionCount); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *SessionProject) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetLastActiveAtMs() {
		if err = oprot.WriteFieldBegin("last_active_at_ms", thrift.I64, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.LastActiveAtMs); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *SessionProject) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SessionProject(%+v)", *p)

}

type AgentThread struct {
	ThreadID       int64             `thrift:"thread_id,1" json:"thread_id,string" form:"thread_id" query:"thread_id"`
	AcNamespace    string            `thrift:"ac_namespace,2" form:"ac_namespace" json:"ac_namespace" query:"ac_namespace"`
	SessionID      int64             `thrift:"session_id,3" json:"session_id,string" form:"session_id" query:"session_id"`
	UID            int64             `thrift:"uid,4" json:"uid,string" form:"uid" query:"uid"`
	Title          *string           `thrift:"title,6,optional" form:"title" json:"title,omitempty" query:"title"`
	Status         AgentThreadStatus `thrift:"status,7" form:"status" json:"status" query:"status"`
	StatusReason   *string           `thrift:"status_reason,8,optional" form:"status_reason" json:"status_reason,omitempty" query:"status_reason"`
	Role           *AgentThreadRole  `thrift:"role,9,optional" form:"role" json:"role,omitempty" query:"role"`
	ParentThreadID *string           `thrift:"parent_thread_id,10,optional" form:"parent_thread_id" json:"parent_thread_id,omitempty" query:"parent_thread_id"`
	RootThreadID   *string           `thrift:"root_thread_id,11,optional" form:"root_thread_id" json:"root_thread_id,omitempty" query:"root_thread_id"`
	CreatedAtMs    *int64            `thrift:"created_at_ms,14,optional" form:"created_at_ms" json:"created_at_ms,omitempty" query:"created_at_ms"`
	UpdatedAtMs    *int64            `thrift:"updated_at_ms,15,optional" form:"updated_at_ms" json:"updated_at_ms,omitempty" query:"updated_at_ms"`
}

func NewAgentThread() *AgentThread {
	return &AgentThread{}
}

func (p *AgentThread) InitDefault() {
}

func (p *AgentThread) GetThreadID() (v int64) {
	return p.ThreadID
}

func (p *AgentThread) GetAcNamespace() (v string) {
	return p.AcNamespace
}

func (p *AgentThread) GetSessionID() (v int64) {
	return p.SessionID
}

func (p *AgentThread) GetUID() (v int64) {
	return p.UID
}

var AgentThread_Title_DEFAULT string

func (p *AgentThread) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return AgentThread_Title_DEFAULT
	}
	return *p.Title
}

func (p *AgentThread) GetStatus() (v AgentThreadStatus) {
	return p.Status
}

var AgentThread_StatusReason_DEFAULT string

func (p *AgentThread) GetStatusReason() (v string) {
	if !p.IsSetStatusReason() {
		return AgentThread_StatusReason_DEFAULT
	}
	return *p.StatusReason
}

var AgentThread_Role_DEFAULT AgentThreadRole

func (p *AgentThread) GetRole() (v AgentThreadRole) {
	if !p.IsSetRole() {
		return AgentThread_Role_DEFAULT
	}
	return *p.Role
}

var AgentThread_ParentThreadID_DEFAULT string

func (p *AgentThread) GetParentThreadID() (v string) {
	if !p.IsSetParentThreadID() {
		return AgentThread_ParentThreadID_DEFAULT
	}
	return *p.ParentThreadID
}

var AgentThread_RootThreadID_DEFAULT string

func (p *AgentThread) GetRootThreadID() (v string) {
	if !p.IsSetRootThreadID() {
		return AgentThread_RootThreadID_DEFAULT
	}
	return *p.RootThreadID
}

var AgentThread_CreatedAtMs_DEFAULT int64

func (p *AgentThread) GetCreatedAtMs() (v int64) {
	if !p.IsSetCreatedAtMs() {
		return AgentThread_CreatedAtMs_DEFAULT
	}
	return *p.CreatedAtMs
}

var AgentThread_UpdatedAtMs_DEFAULT int64

func (p *AgentThread) GetUpdatedAtMs() (v int64) {
	if !p.IsSetUpdatedAtMs() {
		return AgentThread_UpdatedAtMs_DEFAULT
	}
	return *p.UpdatedAtMs
}

var fieldIDToName_AgentThread = map[int16]string{
	1:  "thread_id",
	2:  "ac_namespace",
	3:  "session_id",
	4:  "uid",
	6:  "title",
	7:  "status",
	8:  "status_reason",
	9:  "role",
	10: "parent_thread_id",
	11: "root_thread_id",
	14: "created_at_ms",
	15: "updated_at_ms",
}

func (p *AgentThread) IsSetTitle() bool {
	return p.Title != nil
}

func (p *AgentThread) IsSetStatusReason() bool {
	return p.StatusReason != nil
}

func (p *AgentThread) IsSetRole() bool {
	return p.Role != nil
}

func (p *AgentThread) IsSetParentThreadID() bool {
	return p.ParentThreadID != nil
}

func (p *AgentThread) IsSetRootThreadID() bool {
	return p.RootThreadID != nil
}

func (p *AgentThread) IsSetCreatedAtMs() bool {
	return p.CreatedAtMs != nil
}

func (p *AgentThread) IsSetUpdatedAtMs() bool {
	return p.UpdatedAtMs != nil
}

func (p *AgentThread) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("AgentThread")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 9:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField9(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 10:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField10(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 11:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField11(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 14:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField14(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 15:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField15(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_AgentThread[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *AgentThread) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.ThreadID = _field
	return nil
}
func (p *AgentThread) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.AcNamespace = _field
	return nil
}
func (p *AgentThread) ReadField3(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.SessionID = _field
	return nil
}
func (p *AgentThread) ReadField4(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.UID = _field
	return nil
}
func (p *AgentThread) ReadField6(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Title = _field
	return nil
}
func (p *AgentThread) ReadField7(iprot thrift.TProtocol) error {

	var _field AgentThreadStatus
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = AgentThreadStatus(v)
	}
	p.Status = _field
	return nil
}
func (p *AgentThread) ReadField8(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.StatusReason = _field
	return nil
}
func (p *AgentThread) ReadField9(iprot thrift.TProtocol) error {

	var _field *AgentThreadRole
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		tmp := AgentThreadRole(v)
		_field = &tmp
	}
	p.Role = _field
	return nil
}
func (p *AgentThread) ReadField10(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ParentThreadID = _field
	return nil
}
func (p *AgentThread) ReadField11(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.RootThreadID = _field
	return nil
}
func (p *AgentThread) ReadField14(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.CreatedAtMs = _field
	return nil
}
func (p *AgentThread) ReadField15(iprot thrift.TProtocol) error {

	var _field *int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UpdatedAtMs = _field
	return nil
}

func (p *AgentThread) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("AgentThread")

	var fieldId int16
	if err = oprot.WriteStructBegin("AgentThread"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
		if err = p.writeField9(oprot); err != nil {
			fieldId = 9
			goto WriteFieldError
		}
		if err = p.writeField10(oprot); err != nil {
			fieldId = 10
			goto WriteFieldError
		}
		if err = p.writeField11(oprot); err != nil {
			fieldId = 11
			goto WriteFieldError
		}
		if err = p.writeField14(oprot); err != nil {
			fieldId = 14
			goto WriteFieldError
		}
		if err = p.writeField15(oprot); err != nil {
			fieldId = 15
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *AgentThread) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("thread_id", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.ThreadID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *AgentThread) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("ac_namespace", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.AcNamespace); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *AgentThread) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("session_id", thrift.I64, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.SessionID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *AgentThread) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("uid", thrift.I64, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.UID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}
func (p *AgentThread) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetTitle() {
		if err = oprot.WriteFieldBegin("title", thrift.STRING, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Title); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}
func (p *AgentThread) writeField7(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("status", thrift.I32, 7); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI32(int32(p.Status)); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}
func (p *AgentThread) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetStatusReason() {
		if err = oprot.WriteFieldBegin("status_reason", thrift.STRING, 8); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.StatusReason); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}
func (p *AgentThread) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetRole() {
		if err = oprot.WriteFieldBegin("role", thrift.I32, 9); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(int32(*p.Role)); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 end error: ", p), err)
}
func (p *AgentThread) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetParentThreadID() {
		if err = oprot.WriteFieldBegin("parent_thread_id", thrift.STRING, 10); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ParentThreadID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 end error: ", p), err)
}
func (p *AgentThread) writeField11(oprot thrift.TProtocol) (err error) {
	if p.IsSetRootThreadID() {
		if err = oprot.WriteFieldBegin("root_thread_id", thrift.STRING, 11); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.RootThreadID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 end error: ", p), err)
}
func (p *AgentThread) writeField14(oprot thrift.TProtocol) (err error) {
	if p.IsSetCreatedAtMs() {
		if err = oprot.WriteFieldBegin("created_at_ms", thrift.I64, 14); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.CreatedAtMs); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 14 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 14 end error: ", p), err)
}
func (p *AgentThread) writeField15(oprot thrift.TProtocol) (err error) {
	if p.IsSetUpdatedAtMs() {
		if err = oprot.WriteFieldBegin("updated_at_ms", thrift.I64, 15); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI64(*p.UpdatedAtMs); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 15 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 15 end error: ", p), err)
}

func (p *AgentThread) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentThread(%+v)", *p)

}

type MessageRef struct {
	ThreadID  int64  `thrift:"thread_id,1" json:"thread_id,string" form:"thread_id" query:"thread_id"`
	MessageID string `thrift:"message_id,2" form:"message_id" json:"message_id" query:"message_id"`
}

func NewMessageRef() *MessageRef {
	return &MessageRef{}
}

func (p *MessageRef) InitDefault() {
}

func (p *MessageRef) GetThreadID() (v int64) {
	return p.ThreadID
}

func (p *MessageRef) GetMessageID() (v string) {
	return p.MessageID
}

var fieldIDToName_MessageRef = map[int16]string{
	1: "thread_id",
	2: "message_id",
}

func (p *MessageRef) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("MessageRef")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MessageRef[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MessageRef) ReadField1(iprot thrift.TProtocol) error {

	var _field int64
	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		_field = v
	}
	p.ThreadID = _field
	return nil
}
func (p *MessageRef) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.MessageID = _field
	return nil
}

func (p *MessageRef) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("MessageRef")

	var fieldId int16
	if err = oprot.WriteStructBegin("MessageRef"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MessageRef) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("thread_id", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.ThreadID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *MessageRef) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("message_id", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.MessageID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *MessageRef) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageRef(%+v)", *p)

}

type ResumeRef struct {
	TurnID       string `thrift:"turn_id,1" form:"turn_id" json:"turn_id" query:"turn_id"`
	CheckpointID string `thrift:"checkpoint_id,2" form:"checkpoint_id" json:"checkpoint_id" query:"checkpoint_id"`
	InterruptID  string `thrift:"interrupt_id,3" form:"interrupt_id" json:"interrupt_id" query:"interrupt_id"`
}

func NewResumeRef() *ResumeRef {
	return &ResumeRef{}
}

func (p *ResumeRef) InitDefault() {
}

func (p *ResumeRef) GetTurnID() (v string) {
	return p.TurnID
}

func (p *ResumeRef) GetCheckpointID() (v string) {
	return p.CheckpointID
}

func (p *ResumeRef) GetInterruptID() (v string) {
	return p.InterruptID
}

var fieldIDToName_ResumeRef = map[int16]string{
	1: "turn_id",
	2: "checkpoint_id",
	3: "interrupt_id",
}

func (p *ResumeRef) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("ResumeRef")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ResumeRef[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ResumeRef) ReadField1(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.TurnID = _field
	return nil
}
func (p *ResumeRef) ReadField2(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.CheckpointID = _field
	return nil
}
func (p *ResumeRef) ReadField3(iprot thrift.TProtocol) error {

	var _field string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = v
	}
	p.InterruptID = _field
	return nil
}

func (p *ResumeRef) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("ResumeRef")

	var fieldId int16
	if err = oprot.WriteStructBegin("ResumeRef"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ResumeRef) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("turn_id", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.TurnID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *ResumeRef) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("checkpoint_id", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.CheckpointID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *ResumeRef) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("interrupt_id", thrift.STRING, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.InterruptID); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *ResumeRef) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResumeRef(%+v)", *p)

}

type ApprovalInput struct {
	Approved       bool    `thrift:"approved,1" form:"approved" json:"approved" query:"approved"`
	Reason         *string `thrift:"reason,2,optional" form:"reason" json:"reason,omitempty" query:"reason"`
	AllowInSession *bool   `thrift:"allow_in_session,3,optional" form:"allow_in_session" json:"allow_in_session,omitempty" query:"allow_in_session"`
	// 用户响应的是哪个工具审批。前端从 timeline event_json 的 approval payload 原样带回，
	// worker 用它写入 session 级审批复用规则。
	ToolName      *string `thrift:"tool_name,4,optional" form:"tool_name" json:"tool_name,omitempty" query:"tool_name"`
	ArgumentsJSON *string `thrift:"arguments_json,5,optional" form:"arguments_json" json:"arguments_json,omitempty" query:"arguments_json"`
}

func NewApprovalInput() *ApprovalInput {
	return &ApprovalInput{}
}

func (p *ApprovalInput) InitDefault() {
}

func (p *ApprovalInput) GetApproved() (v bool) {
	return p.Approved
}

var ApprovalInput_Reason_DEFAULT string

func (p *ApprovalInput) GetReason() (v string) {
	if !p.IsSetReason() {
		return ApprovalInput_Reason_DEFAULT
	}
	return *p.Reason
}

var ApprovalInput_AllowInSession_DEFAULT bool

func (p *ApprovalInput) GetAllowInSession() (v bool) {
	if !p.IsSetAllowInSession() {
		return ApprovalInput_AllowInSession_DEFAULT
	}
	return *p.AllowInSession
}

var ApprovalInput_ToolName_DEFAULT string

func (p *ApprovalInput) GetToolName() (v string) {
	if !p.IsSetToolName() {
		return ApprovalInput_ToolName_DEFAULT
	}
	return *p.ToolName
}

var ApprovalInput_ArgumentsJSON_DEFAULT string

func (p *ApprovalInput) GetArgumentsJSON() (v string) {
	if !p.IsSetArgumentsJSON() {
		return ApprovalInput_ArgumentsJSON_DEFAULT
	}
	return *p.ArgumentsJSON
}

var fieldIDToName_ApprovalInput = map[int16]string{
	1: "approved",
	2: "reason",
	3: "allow_in_session",
	4: "tool_name",
	5: "arguments_json",
}

func (p *ApprovalInput) IsSetReason() bool {
	return p.Reason != nil
}

func (p *ApprovalInput) IsSetAllowInSession() bool {
	return p.AllowInSession != nil
}

func (p *ApprovalInput) IsSetToolName() bool {
	return p.ToolName != nil
}

func (p *ApprovalInput) IsSetArgumentsJSON() bool {
	return p.ArgumentsJSON != nil
}

func (p *ApprovalInput) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("ApprovalInput")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ApprovalInput[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ApprovalInput) ReadField1(iprot thrift.TProtocol) error {

	var _field bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = v
	}
	p.Approved = _field
	return nil
}
func (p *ApprovalInput) ReadField2(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Reason = _field
	return nil
}
func (p *ApprovalInput) ReadField3(iprot thrift.TProtocol) error {

	var _field *bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.AllowInSession = _field
	return nil
}
func (p *ApprovalInput) ReadField4(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ToolName = _field
	return nil
}
func (p *ApprovalInput) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ArgumentsJSON = _field
	return nil
}

func (p *ApprovalInput) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("ApprovalInput")

	var fieldId int16
	if err = oprot.WriteStructBegin("ApprovalInput"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ApprovalInput) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("approved", thrift.BOOL, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteBool(p.Approved); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *ApprovalInput) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetReason() {
		if err = oprot.WriteFieldBegin("reason", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Reason); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}
func (p *ApprovalInput) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetAllowInSession() {
		if err = oprot.WriteFieldBegin("allow_in_session", thrift.BOOL, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteBool(*p.AllowInSession); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}
func (p *ApprovalInput) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetToolName() {
		if err = oprot.WriteFieldBegin("tool_name", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ToolName); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}
func (p *ApprovalInput) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetArgumentsJSON() {
		if err = oprot.WriteFieldBegin("arguments_json", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ArgumentsJSON); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *ApprovalInput) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApprovalInput(%+v)", *p)

}

type AgentSessionView struct {
	Session *AgentSession  `thrift:"session,1" form:"session" json:"session" query:"session"`
	Threads []*AgentThread `thrift:"threads,2,optional" form:"threads" json:"threads,omitempty" query:"threads"`
}

func NewAgentSessionView() *AgentSessionView {
	return &AgentSessionView{}
}

func (p *AgentSessionView) InitDefault() {
}

var AgentSessionView_Session_DEFAULT *AgentSession

func (p *AgentSessionView) GetSession() (v *AgentSession) {
	if !p.IsSetSession() {
		return AgentSessionView_Session_DEFAULT
	}
	return p.Session
}

var AgentSessionView_Threads_DEFAULT []*AgentThread

func (p *AgentSessionView) GetThreads() (v []*AgentThread) {
	if !p.IsSetThreads() {
		return AgentSessionView_Threads_DEFAULT
	}
	return p.Threads
}

var fieldIDToName_AgentSessionView = map[int16]string{
	1: "session",
	2: "threads",
}

func (p *AgentSessionView) IsSetSession() bool {
	return p.Session != nil
}

func (p *AgentSessionView) IsSetThreads() bool {
	return p.Threads != nil
}

func (p *AgentSessionView) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("AgentSessionView")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_AgentSessionView[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *AgentSessionView) ReadField1(iprot thrift.TProtocol) error {
	_field := NewAgentSession()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Session = _field
	return nil
}
func (p *AgentSessionView) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	_field := make([]*AgentThread, 0, size)
	values := make([]AgentThread, size)
	for i := 0; i < size; i++ {
		_elem := &values[i]
		_elem.InitDefault()

		if err := _elem.Read(iprot); err != nil {
			return err
		}

		_field = append(_field, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	p.Threads = _field
	return nil
}

func (p *AgentSessionView) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("AgentSessionView")

	var fieldId int16
	if err = oprot.WriteStructBegin("AgentSessionView"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *AgentSessionView) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("session", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Session.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *AgentSessionView) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetThreads() {
		if err = oprot.WriteFieldBegin("threads", thrift.LIST, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Threads)); err != nil {
			return err
		}
		for _, v := range p.Threads {
			if err := v.Write(oprot); err != nil {
				return err
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *AgentSessionView) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AgentSessionView(%+v)", *p)

}

type PageCursor struct {
	Cursor *string `thrift:"cursor,1,optional" form:"cursor" json:"cursor,omitempty" query:"cursor"`
	Limit  *int32  `thrift:"limit,2,optional" form:"limit" json:"limit,omitempty" query:"limit"`
}

func NewPageCursor() *PageCursor {
	return &PageCursor{}
}

func (p *PageCursor) InitDefault() {
}

var PageCursor_Cursor_DEFAULT string

func (p *PageCursor) GetCursor() (v string) {
	if !p.IsSetCursor() {
		return PageCursor_Cursor_DEFAULT
	}
	return *p.Cursor
}

var PageCursor_Limit_DEFAULT int32

func (p *PageCursor) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return PageCursor_Limit_DEFAULT
	}
	return *p.Limit
}

var fieldIDToName_PageCursor = map[int16]string{
	1: "cursor",
	2: "limit",
}

func (p *PageCursor) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *PageCursor) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *PageCursor) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("PageCursor")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PageCursor[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PageCursor) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Cursor = _field
	return nil
}
func (p *PageCursor) ReadField2(iprot thrift.TProtocol) error {

	var _field *int32
	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.Limit = _field
	return nil
}

func (p *PageCursor) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("PageCursor")

	var fieldId int16
	if err = oprot.WriteStructBegin("PageCursor"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PageCursor) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetCursor() {
		if err = oprot.WriteFieldBegin("cursor", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Cursor); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *PageCursor) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetLimit() {
		if err = oprot.WriteFieldBegin("limit", thrift.I32, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Limit); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PageCursor) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageCursor(%+v)", *p)

}

type PageInfo struct {
	NextCursor *string `thrift:"next_cursor,1,optional" form:"next_cursor" json:"next_cursor,omitempty" query:"next_cursor"`
	HasMore    bool    `thrift:"has_more,2" form:"has_more" json:"has_more" query:"has_more"`
}

func NewPageInfo() *PageInfo {
	return &PageInfo{}
}

func (p *PageInfo) InitDefault() {
}

var PageInfo_NextCursor_DEFAULT string

func (p *PageInfo) GetNextCursor() (v string) {
	if !p.IsSetNextCursor() {
		return PageInfo_NextCursor_DEFAULT
	}
	return *p.NextCursor
}

func (p *PageInfo) GetHasMore() (v bool) {
	return p.HasMore
}

var fieldIDToName_PageInfo = map[int16]string{
	1: "next_cursor",
	2: "has_more",
}

func (p *PageInfo) IsSetNextCursor() bool {
	return p.NextCursor != nil
}

func (p *PageInfo) Read(iprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("PageInfo")

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.BOOL {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PageInfo[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PageInfo) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.NextCursor = _field
	return nil
}
func (p *PageInfo) ReadField2(iprot thrift.TProtocol) error {

	var _field bool
	if v, err := iprot.ReadBool(); err != nil {
		return err
	} else {
		_field = v
	}
	p.HasMore = _field
	return nil
}

func (p *PageInfo) Write(oprot thrift.TProtocol) (err error) {
	apache_warning.WarningApache("PageInfo")

	var fieldId int16
	if err = oprot.WriteStructBegin("PageInfo"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PageInfo) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetNextCursor() {
		if err = oprot.WriteFieldBegin("next_cursor", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.NextCursor); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}
func (p *PageInfo) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("has_more", thrift.BOOL, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteBool(p.HasMore); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PageInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageInfo(%+v)", *p)

}
