// Code generated by hertztool.

package handler

import (
	"context"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	deep_agent_sdk "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/hertz_gen/deep_agent_sdk"
	apisession "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/service/session"
)

// CreateSession .
// @router /ad/deep_agent_sdk/create_session [POST]
func CreateSession(ctx context.Context, c *app.RequestContext) {
	var req deep_agent_sdk.CreateSessionHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.CreateSessionHTTPResponse{BaseResp: baseResp})
		return
	}
	resp, err := apisession.Create(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.CreateSessionHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}
