// Code generated by hertztool.

package handler

import (
	"context"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	deep_agent_sdk "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/hertz_gen/deep_agent_sdk"
	apitimeline "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/service/timeline"
)

// ListTimeline .
// @router /ad/deep_agent_sdk/list_timeline [POST]
func ListTimeline(ctx context.Context, c *app.RequestContext) {
	var req deep_agent_sdk.ListTimelineHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.ListTimelineHTTPResponse{BaseResp: baseResp})
		return
	}
	resp, err := apitimeline.List(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.ListTimelineHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}
