// Code generated by hertztool.

package handler

import (
	"context"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	deep_agent_sdk "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/hertz_gen/deep_agent_sdk"
	apicontrol "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/service/control"
)

// StopRunning .
// @router /ad/deep_agent_sdk/stop_running [POST]
func StopRunning(ctx context.Context, c *app.RequestContext) {
	var req deep_agent_sdk.StopRunningHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.StopRunningHTTPResponse{BaseResp: baseResp})
		return
	}
	resp, err := apicontrol.StopRunning(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.StopRunningHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}
