// Code generated by hertztool.

package handler

import (
	"context"
	"encoding/json"
	"errors"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	deep_agent_sdk "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/hertz_gen/deep_agent_sdk"
	apiinput "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/service/input"
)

// SubmitInput .
// @router /ad/deep_agent_sdk/submit_input [POST]
func SubmitInput(ctx context.Context, c *app.RequestContext) {
	var req deep_agent_sdk.SubmitInputHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.SubmitInputHTTPResponse{BaseResp: baseResp})
		return
	}
	extensions, err := submitInputExtensions(c.Request.Body())
	if writeBindError(c, err) {
		return
	}
	ctx = apiinput.ContextWithResumeInputExtensions(ctx, extensions)
	resp, err := apiinput.Submit(ctx, uid, &req)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.SubmitInputHTTPResponse{BaseResp: baseResp})
		return
	}
	c.JSON(200, resp)
}

func submitInputExtensions(body []byte) (extensions *apiinput.ResumeInputExtensions, err error) {
	var raw struct {
		apiinput.ResumeInputExtensions
		ResumeRef *json.RawMessage `json:"resume_ref"`
		Approval  *struct {
			CancelTurn bool `json:"cancel_turn"`
		} `json:"approval"`
	}
	if len(body) == 0 {
		return nil, nil
	}
	if err := json.Unmarshal(body, &raw); err != nil {
		return nil, err
	}
	if raw.RequestUserInput == nil && raw.Interrupt == nil && raw.ConsumedMessageIDs == nil && raw.Approval == nil {
		return nil, nil
	}
	if raw.ResumeRef == nil {
		return nil, errors.New("resume_ref is required for resume input")
	}
	if raw.Approval != nil {
		raw.ApprovalCancelTurn = raw.Approval.CancelTurn
	}
	return &raw.ResumeInputExtensions, nil
}
