// Code generated by hertztool.

package handler

import (
	"context"
	"io"
	"sync"

	"code.byted.org/middleware/hertz/pkg/app"
	"code.byted.org/middleware/hertz_ext/v2/binding"
	deep_agent_sdk "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/hertz_gen/deep_agent_sdk"
	apitimeline "eino-cli/deepagent/cmd/cloud_agent/deep_agent_sdk/service/timeline"
)

// SubscribeTimeline .
// @router /ad/deep_agent_sdk/subscribe_timeline [POST]
func SubscribeTimeline(ctx context.Context, c *app.RequestContext) {
	var req deep_agent_sdk.SubscribeTimelineHTTPRequest
	if writeBindError(c, binding.BindAndValidate(c, &req)) {
		return
	}

	ctx, uid, err := currentUID(ctx, c)
	if err != nil {
		baseResp, status := commonBaseResp(err)
		c.JSON(status, &deep_agent_sdk.SubscribeTimelineHTTPResponse{BaseResp: baseResp})
		return
	}

	streamCtx, cancel := context.WithCancel(ctx)
	pr, pw := io.Pipe()
	c.SetContentType("text/event-stream; charset=utf-8")
	c.Response.Header.Set("Cache-Control", "no-cache")
	c.Response.ImmediateHeaderFlush = true
	c.SetBodyStream(cancelOnClose(pr, cancel), -1)
	go func() {
		defer cancel()
		defer pw.Close()
		if err := apitimeline.Subscribe(streamCtx, uid, &req, pw); err != nil {
			apitimeline.WriteStreamError(pw, err)
		}
	}()
}

type cancelOnCloseReader struct {
	*io.PipeReader
	cancel context.CancelFunc
	once   sync.Once
	err    error
}

func cancelOnClose(pr *io.PipeReader, cancel context.CancelFunc) io.ReadCloser {
	return &cancelOnCloseReader{PipeReader: pr, cancel: cancel}
}

func (r *cancelOnCloseReader) Close() error {
	r.once.Do(func() {
		r.cancel()
		r.err = r.PipeReader.Close()
	})
	return r.err
}
