CREATE TABLE t_agentthread_history (
  thread_id VARCHAR(128) NOT NULL COMMENT 'deepagent thread id',
  message_id BIGINT UNSIGNED NOT NULL COMMENT 'history record id generated by worker id generator',
  seq BIGINT NOT NULL DEFAULT 0 COMMENT 'per-thread history append sequence',
  turn_id VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'logical turn id',
  type VARCHAR(32) NOT NULL COMMENT 'history record type: message compact',
  message MEDIUMTEXT COMMENT 'serialized agentthread message json',
  ext TEXT COMMENT 'serialized history record extension json',
  created_at BIGINT NOT NULL DEFAULT 0 COMMENT 'record create unix timestamp in seconds',
  PRIMARY KEY (message_id),
  KEY idx_thread_seq (thread_id, seq),
  KEY idx_thread_turn_seq (thread_id, turn_id, seq),
  KEY idx_thread_created_at (thread_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='AIC Agent SDK worker deepagent thread history table';
