// Code generated by hertztool. DO NOT EDIT.

package router

import (
	"code.byted.org/middleware/hertz/pkg/app/server"
	aic_agent_sdk_api "eino-cli/deepagent/cmd/cloud_agent/aic_agent_sdk_api/biz/router/aic_agent_sdk_api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	aic_agent_sdk_api.Register(r)
}
