//go:build bytedance

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"

	"eino-cli/videoagent"
)

func TestDirectMediaProvidersSmoke(t *testing.T) {
	config := directMediaConfig(t)
	ctx, cancel := context.WithTimeout(context.Background(), 45*time.Minute)
	defer cancel()

	t.Run("video_storage", func(t *testing.T) {
		if config.VideoStorage == nil {
			t.Fatal("video storage config is missing")
		}
		if _, err := videoagent.NewBytedanceVideoUploader(*config.VideoStorage); err != nil {
			t.Fatalf("initialize video storage: %v", err)
		}
	})

	t.Run("competition_image", func(t *testing.T) {
		imageClient, err := videoagent.NewArkImageClient(*config.ImageArk)
		if err != nil {
			t.Fatal(err)
		}
		image, err := imageClient.SubmitImage(ctx, videoagent.ImageRequest{
			Prompt:    "一双黑色复古德训女鞋，白色背景，商品棚拍，竖版",
			SubmitKey: "direct-media-smoke:image",
		})
		if err != nil {
			t.Fatalf("submit image: %v", err)
		}
		imageStatus := waitForMediaJob(t, ctx, "image", image, imageClient.GetImage)
		if imageStatus.URI == "" && imageStatus.URL == "" {
			t.Fatal("image completed without uri or url")
		}
	})

	t.Run("prompt_tts", func(t *testing.T) {
		matx, err := videoagent.NewBytedanceMatxClient()
		if err != nil {
			t.Fatal(err)
		}
		ttsClient, err := videoagent.NewPromptTTSClient(*config.PromptTTS, matx)
		if err != nil {
			t.Fatal(err)
		}
		tts, err := ttsClient.SubmitTTS(ctx, videoagent.TTSRequest{
			Prompt:      "年轻女声，清晰自然，适合商品广告旁白",
			Text:        "这双复古德训鞋，轻盈百搭，舒适显高。",
			WithExample: true,
			SubmitKey:   "direct-media-smoke:tts",
		})
		if err != nil {
			t.Fatalf("submit tts: %v", err)
		}
		if tts.Status == nil || tts.Status.URL == "" || tts.Status.ExampleURL == "" {
			t.Fatal("tts completed without narration or example audio url")
		}
	})

	t.Run("seedance_preview", func(t *testing.T) {
		previewClient, err := videoagent.NewSeedanceClient(*config.Seedance, nil)
		if err != nil {
			t.Fatal(err)
		}
		preview, err := previewClient.SubmitPreview(ctx, videoagent.VideoRequest{
			Prompt:      "展示一双复古德训女鞋从鞋盒中取出，镜头缓慢推进，商品广告风格",
			Strategy:    videoagent.PreviewStrategyT2V,
			AspectRatio: "9:16",
			Duration:    5,
			SubmitKey:   "direct-media-smoke:preview",
		})
		if err != nil {
			t.Fatalf("submit preview: %v", err)
		}
		previewStatus := waitForMediaJob(t, ctx, "preview", preview, previewClient.GetPreview)
		if previewStatus.URL == "" {
			t.Fatal("preview completed without display url")
		}
	})
}

func TestDirectFinalVideoSmoke(t *testing.T) {
	config := directMediaConfig(t)
	vid := os.Getenv("VIDEO_AGENT_FINALVIDEO_SMOKE_VID")
	if vid == "" {
		t.Skip("set VIDEO_AGENT_FINALVIDEO_SMOKE_VID to a jichuang vid generated by the preview import step")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Minute)
	defer cancel()
	renderer, err := videoagent.NewBytedanceVideoRenderer(config.FinalVideo.BizID)
	if err != nil {
		t.Fatal(err)
	}
	client, err := videoagent.NewMetaFinalVideoClient(*config.FinalVideo, renderer)
	if err != nil {
		t.Fatal(err)
	}
	previewData, err := json.Marshal(map[string]any{
		"scene_id":         "1",
		"uri":              "vid://" + vid,
		"duration_seconds": 5,
	})
	if err != nil {
		t.Fatal(err)
	}
	finalVideo, err := client.SubmitFinalVideo(ctx, videoagent.VideoRequest{
		ClipScript: &videoagent.ClipScript{Scenes: []videoagent.Scene{{
			ID: "1", Visual: "展示复古德训女鞋", Voiceover: "轻盈百搭", DurationMS: 5000,
		}}},
		Inputs: []videoagent.Artifact{{
			ID: "preview:1", Kind: "preview_video", Status: string(videoagent.Succeeded), Data: previewData,
		}},
		SubmitKey: "direct-media-smoke:finalvideo",
	})
	if err != nil {
		t.Fatalf("submit finalvideo: %v", err)
	}
	finalStatus := waitForMediaJob(t, ctx, "finalvideo", finalVideo, client.GetFinalVideo)
	if finalStatus.URI == "" || finalStatus.URL == "" {
		t.Fatal("finalvideo completed without vid or display url")
	}

	t.Log("direct meta finalvideo provider succeeded")
}

func directMediaConfig(t *testing.T) videoagent.RemoteConfig {
	t.Helper()
	if os.Getenv("VIDEO_AGENT_DIRECT_MEDIA_SMOKE") != "1" {
		t.Skip("set VIDEO_AGENT_DIRECT_MEDIA_SMOKE=1 to call direct media providers")
	}
	configPath := os.Getenv("VIDEO_AGENT_MEDIA_CONFIG")
	if configPath == "" {
		t.Fatal("VIDEO_AGENT_MEDIA_CONFIG is required")
	}
	config, err := readJSON[videoagent.RemoteConfig](configPath)
	if err != nil {
		t.Fatal(err)
	}
	if config.ImageArk == nil || config.PromptTTS == nil || config.Seedance == nil || config.FinalVideo == nil {
		t.Fatal(fmt.Errorf("media config is missing at least one required provider"))
	}
	return config
}

func waitForMediaJob(t *testing.T, ctx context.Context, name string, job videoagent.SubmittedJob, get func(context.Context, string) (videoagent.JobStatus, error)) videoagent.JobStatus {
	t.Helper()
	if job.Status != nil {
		if job.Status.State == videoagent.JobSucceeded {
			return *job.Status
		}
		if job.Status.State == videoagent.JobFailed {
			t.Fatalf("%s task failed: %s", name, job.Status.Message)
		}
	}
	if job.JobID == "" {
		t.Fatalf("%s submission returned no job id", name)
	}

	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()
	for {
		status, err := get(ctx, job.JobID)
		if err != nil {
			t.Fatalf("get %s status: %v", name, err)
		}
		switch status.State {
		case videoagent.JobSucceeded:
			return status
		case videoagent.JobFailed:
			t.Fatalf("%s task failed: %s", name, status.Message)
		}
		select {
		case <-ctx.Done():
			t.Fatalf("wait for %s: %v", name, ctx.Err())
		case <-ticker.C:
		}
	}
}
